GPU_ID: '-1'
WORKERS: 1
CUDA: False
LOGDIR: 'filmac'
COMET_PROJECT_NAME: 'local'

TRAIN:
    FLAG: True
    LEARNING_RATE: 0.0002
    # LEARNING_RATE: 0.0001
    BATCH_SIZE: 128
    # BATCH_SIZE: 64
    MAX_EPOCHS: 30
    SNAPSHOT_INTERVAL: 5
    WEIGHT_INIT: "xavier_uniform"
    EALRY_STOPPING: True
    PATIENCE: 5
    CLIP_GRADS: True
    RADAM: False
    # MAX_STEPS: 4

DATASET:
    # DATA_DIR: '/storage1/datasets/CLEVR_v1.0/features'
    DATA_DIR: '/Users/sebamenabar/Documents/datasets/CLEVR/CLEVR_v1.0/data'
    IGNORE_TOKEN: ''

model:
    max_step: 4
    separate_syntax_semantics: False
    common:
        module_dim: 512
    input_unit:
        wordvec_dim: 300
        rnn_dim: 512
        bidirectional: True
        separate_syntax_semantics_embeddings: False
        stem_act: 'ELU'
    control_unit:
        control_feed_prev: True
        control_cont_activation: 'TANH'
    read_unit:
        num_blocks: 1
        film_from: 'qi'
    write_unit:
        rtom: False
        self_attn: True
        gate: True
        gate_shared: False
    # output_unit: