GPU_ID: '-1'
WORKERS: 1
CUDA: False

TRAIN:
    FLAG: True
    LEARNING_RATE: 0.0001
    BATCH_SIZE: 64
    MAX_EPOCHS: 200
    SNAPSHOT_INTERVAL: 100
    WEIGHT_INIT: "xavier_uniform"
    EALRY_STOPPING: True
    PATIENCE: 5
    CLIP_GRADS: True
    RADAM: False
    # MAX_STEPS: 4

DATASET:
    DATA_DIR: '/Users/sebamenabar/Documents/datasets/CLEVR/CLEVR_v1.0/data'
    SCENES_DIR: '/Users/sebamenabar/Documents/datasets/CLEVR/CLEVR_v1.0/scenes/'

model:
    num_lobs: 10
    max_step: 4
    separate_syntax_semantics: False
    common:
        module_dim: 256
    input_unit:
        wordvec_dim: 256
        rnn_dim: 256
        bidirectional: True
        separate_syntax_semantics_embeddings: False
        # num_lobs: 0
    # control_unit:
    # read_unit:
    write_unit:
        rtom: True
    # output_unit: 
